app/urls.py
from django.contrib import admin
from django.urls import path, include

from app.settings import DEBUG

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
    path("movies/", include("movie.urls", namespace="movies")),
    path("user/", include("users.urls", namespace="user")),
    path("", include("main.urls", namespace="main")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

storelink/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import main

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", include("main.urls"), name="home"),
    path("", main, name="home"),
]

storelinks/urls.py
from django.contrib import admin
from django.urls import path, include

from storelinks.settings import DEBUG

urlpatterns = [
    path("", include("movie.urls", namespace="movie")),
    path("about/", include("about.urls", namespace="about")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    # path("movies/", include("movie.urls", namespace="movie")),
    path("summernote/", include("django_summernote.urls")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    image = models.ImageField(
        upload_to="profile_images", null=True, blank=True, verbose_name="Avatar"
    )

    class Meta:
        db_table = "user"
        verbose_name = "User"
        verbose_name_plural = "Users"

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from django.contrib.auth.forms import (
    AuthenticationForm,
    UserCreationForm,
    UserChangeForm,
    )

from users.models import User


class UserLoginForm(AuthenticationForm):
    """
    This class represents a user login form used for authentication.
    """

    username = forms.CharField()
    password = forms.CharField()

    class Meta:
        model = User
        fields = ("username", "password")


class UserRegisterForm(UserCreationForm):
    """
    User registration form class extending UserCreationForm.
    """

    class Meta:
        model = User
        fields = (
            "first_name",
            "last_name",
            "username",
            "email",
            "password1",
            "password2",
            )

    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    username = forms.CharField()
    email = forms.EmailField()
    password1 = forms.CharField()
    password2 = forms.CharField()


class UserProfileForm(UserChangeForm):
    """
             A form for updating user profiles, inheriting from UserChangeForm.
             This form includes the fields for the user's profile image, first
             name, last name, email, and username.

    """

    class Meta:
        model = User
        fields = (
            "image",
            "first_name",
            "last_name",
            "email",
            "username",
            )

    image = forms.ImageField(required=False)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    email = forms.EmailField()
    username = forms.CharField()

users/views.py
from django.contrib import auth, messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse

from movie.models import MovieComment
from users.forms import UserLoginForm, UserRegisterForm, UserProfileForm


# Create your views here.


def login(request):
    """
    Handles the login functionality for users.
    """
    if request.method == "POST":
        form = UserLoginForm(data=request.POST)
        if form.is_valid():
            username = request.POST["username"]
            password = request.POST["password"]
            user = auth.authenticate(username=username, password=password)
            if user:
                auth.login(request, user)
                messages.success(
                    request, f"{username} you logged in Successfully !!")
                if request.POST.get("next", None):
                    return HttpResponseRedirect(request.POST.get["next"])

                return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserLoginForm()

    context = {
        "title": "StoreLinks - LogIn",
        "form": form,
        }

    return render(request, "users/login.html", context)


def registration(request):
    """
    Handles user registration by processing a POST request with user data.
    """
    if request.method == "POST":
        form = UserRegisterForm(data=request.POST)
        if form.is_valid():
            form.save()
            user = form.instance
            auth.login(request, user)
            messages.success(
                request, f"Account created for {user.username} !!")
            return HttpResponseRedirect(reverse("main:index"))
    else:
        form = UserRegisterForm()

    context = {
        "title": "StoreLinks - Registration",
        "form": form,
        }
    return render(request, "users/registration.html", context)


@login_required
def profile(request):
    """
    Handles the profile view for updating user profile information.
    """
    comments = MovieComment.objects.filter(author_id=request.user)
    if request.method == "POST":
        form = UserProfileForm(
            data=request.POST, instance=request.user, files=request.FILES
            )
        if form.is_valid():
            form.save()
            messages.success(
                request, f"Profile updated for {request.user.username} !!")
            return HttpResponseRedirect(reverse("users:profile"))
    else:
        form = UserProfileForm(instance=request.user)
    context = {
        "title": "StoreLinks - Profile",
        "form": form,
        "comments": comments,
        }
    return render(request, "users/profile.html", context)


@login_required
def logout(request):
    """
    Logs out the current authenticated user and redirects to the movie catalog.
    """
    messages.success(request, f"You have been logged out successfully !!")
    auth.logout(request)
    return HttpResponseRedirect(reverse("main:index"))


@login_required
def user_comments(request, slug, comment_id, action=None):
    pass

users/templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-6 bg-white p-4 mb-4 mx-3 rounded custom-shadow">
                    <h2 class="text-center mb-4">Authorization</h2>
                    <form method="post" action="{% url 'users:login' %}">
                        {% csrf_token %}
                        {% if request.GET.next %}
                        	<input type="hidden" name="next" value="{{ request.GET.next }}"/>
                        {% endif %} 
                        <div class="mb-3">
                            <label for="username" class="form-label">User name</label>
                            <input type="text" class="form-control" id="username" name="username"
                                   placeholder="Enter your user name" required
                                   value="{% if form.username.value %}{{ form.username.value }}{% endif %}">
                        </div>
                        <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password"
                                   placeholder="Enter your password" required>
                        </div>
                        <button type="submit" class="btn btn-dark btn-block">Enter</button>
                    </form>
                    <div class="mt-3">
                        <a href="{% url 'users:registration' %}">Create account</a>
                    </div>
                    <hr>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

users/templates/users/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <div class="container">
        <div class="row">
            <div class="container mt-5">
                <div class="row">
                    <!-- User Profile -->
                    <div class="col-md-5">
                        <div class=" bg-white p-4 mb-4 mx-2 rounded custom-shadow">
                            <h3 class="text-center mb-4">{{ user.username }} profile</h3>

                            <form action="{% url 'users:profile' %}" method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="row">
                                    <div class="col-md-12 mb-3 text-center">
                                        {% if user.image %}
                                            <img src="{{ user.image.url }}"
                                                 alt="User avatar" class="img-fluid rounded-circle"
                                                 style="max-width: 150px;">
                                        {% else %}
                                            <img src="{% static 'images/no_image_profile.png' %}"
                                                 alt="User avatar" class="img-fluid rounded-circle"
                                                 style="max-width: 150px;">
                                        {% endif %}
                                        <input type="file" class="form-control mt-3" id="image"
                                               name="image"
                                               accept="image/*">
                                        {% if form.image.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.image.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_first_name" class="form-label">Name</label>
                                        <input type="text"
                                               class="form-control"
                                               id="id_first_name"
                                               name="first_name"
                                               placeholder="Enter your name"
                                               value="{{ user.first_name }}"
                                        >
                                        {% if form.first_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_last_name" class="form-label">Surname</label>
                                        <input type="text"
                                               class="form-control"
                                               id="id_last_name"
                                               name="last_name"
                                               placeholder="Enter your Surname"
                                               value="{{ user.last_name }}"
                                        >
                                        {% if form.last_name.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_username" class="form-label">User name*</label>
                                        <input type="text"
                                               class="form-control"
                                               id="id_username"
                                               name="username"
                                               placeholder="Enter your user name"
                                               value="{{ user.username }}"
                                               required>
                                        {% if form.username.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                        {% endif %}
                                    </div>
                                    <div class="col-md-12 mb-3">
                                        <label for="id_email" class="form-label">Email*</label>
                                        <input type="email"
                                               class="form-control"
                                               id="id_email"
                                               name="email"
                                               placeholder="Enter your email *youremail@example.com"
                                               value="{{ user.email }}"
                                               required>
                                        {% if form.email.errors %}
                                            <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                        {% endif %}
                                    </div>
                                </div>
                                <button type="submit" class="btn btn-dark">Save</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <div class="row">
        <div class="container mt-5">
            <div class="row justify-content-center">
                <div class="col-md-9 bg-white p-4 mb-5 mx-2 rounded custom-shadow">
                    <h2 class="text-center mb-4">Registration</h2>
                    <form method="post" action="{% url 'user:registration' %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-md-6 mb-3">
                                <label for="id_first_name" class="form-label">Name</label>
                                <input type="text" class="form-control" id="id_first_name"
                                       value="{% if form.first_name.value %}{{ form.first_name.value }}{% endif %}"
                                       name="first_name"
                                       placeholder="Enter your Name">
                            {% if form.first_name.errors %}
                            	<div class="alert alert-danger alert-dismissible fade show">{{ form.first_name.errors }}</div>
                            {% endif %} 
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_last_name" class="form-label">Surname</label>
                                <input type="text" class="form-control" id="id_last_name"
                                       value="{% if form.last_name.value %}{{ form.last_name.value }}{% endif %}"
                                       name="last_name"
                                       placeholder="Enter your Surname" >
                                {% if form.last_name.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.last_name.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_username" class="form-label">User name*</label>
                                <input type="text" class="form-control" id="id_username"
                                       value="{% if form.username.value %}{{ form.username.value }}{% endif %}"
                                       name="username"
                                       placeholder="Enter your user name" >
                                {% if form.username.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.username.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_email" class="form-label">Email*</label>
                                <input type="email" class="form-control" id="id_email"
                                       value="{% if form.email.value %}{{ form.email.value }}{% endif %}"
                                       name="email"
                                       placeholder="Enter your email" required>
                                {% if form.email.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.email.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="id_password1" class="form-label">Password*</label>
                                <input type="password" class="form-control" id="id_password1"
                                       value="{% if form.password1.value %}{{ form.password1.value }}{% endif %}"
                                       name="password1"
                                       placeholder="Enter password" required>
                                {% if form.password1.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password1.errors }}</div>
                                {% endif %}
                            </div>
                            <div class="col-md-6 mb-3">
                                <label for="password2" class="form-label">Password confirmation*</label>
                                <input type="password" class="form-control" id="password2"
                                       value="{% if form.password2.value %}{{ form.password2.value }}{% endif %}"
                                       name="password2"
                                       placeholder="Confirm password" required>
                                {% if form.password2.errors %}
                                    <div class="alert alert-danger alert-dismissible fade show">{{ form.password2.errors }}</div>
                                {% endif %}
                            </div>
                        </div>
                        <button type="submit"
                                class="btn btn-dark btn-block">Register</button>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}