app/urls.py
from django.contrib import admin
from django.urls import path, include

from app.settings import DEBUG

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
    path("movies/", include("movie.urls", namespace="movies")),
    path("user/", include("users.urls", namespace="user")),
    path("", include("main.urls", namespace="main")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

movie/urls.py
from django.urls import path

from . import views

app_name = "movies"

urlpatterns = [
    path("", views.movie_catalog, name="movie_catalog"),
    path("search/", views.movie_catalog, name="movie_search"),
    path("<slug:genre_slug>/", views.movie_catalog, name="movie_genre"),
    path("movie/<slug:movie_slug>/", views.movie_detail, name="movie_detail"),
    path(
        "movie/<slug:slug>/edit_comment/<int:comment_id>/",
        views.comment_edit,
        name="comment_edit",
    ),
    path(
        "movie/<slug:slug>/delete_comment/<int:comment_id>/",
        views.comment_delete,
        name="comment_delete",
    ),
]

storelink/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import main

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", include("main.urls"), name="home"),
    path("", main, name="home"),
]

storelinks/urls.py
from django.contrib import admin
from django.urls import path, include

from storelinks.settings import DEBUG

urlpatterns = [
    path("", include("movie.urls", namespace="movie")),
    path("about/", include("about.urls", namespace="about")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    # path("movies/", include("movie.urls", namespace="movie")),
    path("summernote/", include("django_summernote.urls")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

main/forms.py
from django import forms
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    UsernameField,
    )
from django.contrib.auth.models import User
from django.utils.translation import gettext, gettext_lazy as _

# Default user creation form
class SignUpForm(UserCreationForm):
    """
        SignUpForm class extending UserCreationForm for user registration.

        Fields:
            password1: Password field with 'Password' label, using PasswordInput widget with form-control class.
            password2: Password confirmation field with 'Confirm Password (again)' label, using PasswordInput widget with form-control class.

        Meta:
            model: Specifies the User model.
            fields: List of fields to be included in the form - username, first_name, last_name, email.
            labels: Custom labels for first_name, last_name, and email fields.
            widgets: Custom widgets for username, first_name, last_name, and email fields to include form-control class.
    """
    password1 = forms.CharField(
        label="Password", widget=forms.PasswordInput(attrs={"class": "form-control"})
        )
    password2 = forms.CharField(
        label="Confirm Password (again)",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        )
    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]
        labels = {
            "first_name": "First Name",
            "last_name": "Last Name",
            "email": "Email",
            }
        widgets = {
            "username": forms.TextInput(attrs={"class": "form-control"}),
            "first_name": forms.TextInput(attrs={"class": "form-control"}),
            "last_name": forms.TextInput(attrs={"class": "form-control"}),
            "email": forms.EmailInput(attrs={"class": "form-control"}),
            }

# Default authentication form
class LoginForm(AuthenticationForm):
    """
    LoginForm class extends the AuthenticationForm to provide custom styling and widget attributes for the username and password fields.

    Attributes:
        username: A UsernameField instance using a TextInput widget with autofocus and CSS class "form-control".
        password: A CharField instance for the password, with a PasswordInput widget that has the attributes for autocomplete set to "current-password" and CSS class "form-control".
    """
    username = UsernameField(
        widget=forms.TextInput(attrs={"autofocus": True, "class": "form-control"})
        )
    password = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(
            attrs={"autocomplete": "current-password", "class": "form-control"}
            ),
        )

main/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_list_or_404

from movie.models import Movie


def index(request):

    movies_list = get_list_or_404(Movie.objects.filter(status=1).order_by('?'))

    paginator = Paginator(movies_list, 24, orphans=3)
    page_obj = paginator.get_page(1)

    context = {"title": "StoreLinks - Home page", "page_obj": page_obj}

    return render(request, "main/main.html", context)

main/templates/main/main.html
{% extends 'base.html' %}
{% load static %}
{% load movies_tags %}
{% movie_categories_random as page_obj %}

{% block content %}
    <!-- Card 5 - Bootstrap Brain Component -->
    <section class="py-3 py-md-5 py-xl-8 bg-white">
        <div class="container overflow-hidden">
            <div class="row gy-4 gy-xxl-5">
                {% for movie in page_obj %}
                    <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
                        <div class="card border border-dark"
                             style="--bs-card-border-radius: 0; --bs-card-inner-border-radius: 0;">
                            <figure class="card-img-top m-0 overflow-hidden bsb-overlay-hover"
                                    style="height: 380px;">
                                <a href="{% url 'movies:movie_detail' movie.slug %}">
                                    <img class="img-fluid w-100 h-100 bsb-scale bsb-hover-scale-up" loading="lazy"
                                         src="{{ movie.poster }}" alt="{{ movie.title }}"
                                         onerror="this.onerror=null; this.src='{% static 'images/no_image_poster.png' %}';"
                                         style="object-fit: cover;">
                                </a>
                                <figcaption class="p-3">
                                    <h2 class="h3 text-white text-center fw-bold mb-1 bsb-hover-fadeInRight">
                                        {{ movie.title }}
                                    </h2>
                                    {# <p class="fs-7 mb-4 text-white opacity-75 bsb-hover-fadeInLeft">{{ movie.genre }}</p> #}
                                    <p class="fs-9 m-0 px-4 text-white text-center bsb-hover-fadeInUp">
                                        {{ movie.plot }}
                                    </p>
                                </figcaption>
                            </figure>
                        </div>
                    </div>

                {% endfor %}
            </div>
        </div>

    </section>




{% endblock %}