about/urls.py
from django.urls import path

from about import views

app_name = "about"

urlpatterns = [
    path("", views.about, name="about"),
    path("contact/", views.contact, name="contact_us"),
]

app/urls.py
from django.contrib import admin
from django.urls import path, include

from app.settings import DEBUG

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
    path("movies/", include("movie.urls", namespace="movies")),
    path("user/", include("users.urls", namespace="user")),
    path("", include("main.urls", namespace="main")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

storelink/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import main

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", include("main.urls"), name="home"),
    path("", main, name="home"),
]

storelinks/urls.py
from django.contrib import admin
from django.urls import path, include

from storelinks.settings import DEBUG

urlpatterns = [
    path("", include("movie.urls", namespace="movie")),
    path("about/", include("about.urls", namespace="about")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    # path("movies/", include("movie.urls", namespace="movie")),
    path("summernote/", include("django_summernote.urls")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

about/models.py
from cloudinary.models import CloudinaryField
from django.db import models

# Create your models here.


class About(models.Model):
    """
    Store a single page About the site
    """

    title = models.CharField(max_length=200)
    updated_on = models.DateTimeField(auto_now=True)

    class Meta:
        db_table = "about"

        verbose_name = "About section"
        verbose_name_plural = "About sections"

    def __str__(self):
        return self.title


class CollaborateRequest(models.Model):
    """
    Stores a single collaboration request message
    """

    name = models.CharField(max_length=200)
    email = models.EmailField()
    message = models.TextField()
    phone = models.CharField(max_length=25, null=True, blank=True)
    subject = models.CharField(max_length=200, null=True, blank=True)
    read = models.BooleanField(default=False)

    class Meta:
        verbose_name = "Collaboration Request"
        verbose_name_plural = "Collaboration Requests"

    def __str__(self):
        return f"Collaboration request from {self.name}"

about/forms.py
from django import forms

from .models import CollaborateRequest


class CollaborateForm(forms.ModelForm):
    """
    CollaborateForm is a ModelForm for handling collaboration requests.
    """
    class Meta:
        model = CollaborateRequest
        fields = ('name', 'email', 'phone', 'subject', 'message')

about/views.py
from django.shortcuts import render
from .models import About
from .forms import CollaborateForm
from django.contrib import messages


def about(request):
    """
    Renders the About page
    """
    about_field = About.objects.all().order_by("-updated_on").first()
    collaborate_form = CollaborateForm()
    title = "StoreLinks - About"

    return render(
        request,
        "about/about.html",
        {
            "about": about_field,
            "collaborate_form": collaborate_form,
            "title": title,
            },
        )


def contact(request):
    """
    Renders the Contact page
    """
    if request.method == "POST":
        collaborate_form = CollaborateForm(request.POST)
        if collaborate_form.is_valid():
            collaborate_form.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                f"Collaboration request received!"
                f"I endeavour to respond within 2 working days.",
                )
    collaborate_form = CollaborateForm()
    title = "StoreLinks - Contact"

    return render(
        request,
        "about/contact.html",
        {
            "collaborate_form": collaborate_form,
            "title": title,
            },
        )

about/templates/about/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <!-- Page Header - Bootstrap Brain Component -->
    <section class="py-4 py-md-5 py-xl-8">
    <h2 class="visually-hidden">About section</h2>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="container-fluid border border-dark bsb-tpl-bg-gradient-1x">
                        <div class="row justify-content-md-center align-items-center">
                            <div class="col-12 col-md-11 col-xl-10">
                                <div class="page-header-wrapper py-3 py-md-5 py-xl-8">
                                    <h1 class="display-3 text-center fw-bold mb-3 mb-xl-4">About Us</h1>
                                    <p class="lead">
                                        <span class="col-12 col-sm-11 col-lg-8 col-xl-7 col-xxl-6">
                                        Welcome to StoreLinks, your go-to destination for everything movies and music!
                                        We’re passionate about curating a space where film buffs, music lovers, and
                                        content creators can come together to explore, share, and store the best of what
                                        the entertainment world has to offer.
                                        </span>
                                    </p>

                                    <h2 class="display-3 text-center fw-bold mb-3 mb-xl-4">Our Mission</h2>
                                    <p class="lead">
                                        <span class="col-12 col-sm-11 col-lg-8 col-xl-7 col-xxl-6">
                                        At StoreLinks, our mission is simple: to connect people through the power of
                                        film and music. We aim to be a comprehensive platform that not only stores your
                                        favorite links but also helps you discover new content, engage in meaningful
                                        discussions, and stay informed about the latest trends in the industry.
                                        </span>
                                    </p>

                                    <h2 class="display-3 text-center fw-bold mb-3 mb-xl-4">What We Offer</h2>
                                    <p class="lead">
                                        <span class="col-12 col-sm-11 col-lg-8 col-xl-7 col-xxl-6">
                                        Personalized Link Storage: Easily save, categorize, and access your favorite
                                        links related to movies and music, all in one convenient place.
                                        Curated Content: From the latest blockbuster releases to underground music gems,
                                        our platform provides curated lists, expert reviews, and personalized
                                        recommendations tailored to your tastes.
                                        Community Engagement: Join a vibrant community of like-minded individuals. Share
                                        your thoughts, write reviews, and participate in discussions about the content
                                        you love.
                                        In-Depth Information: Dive deep into the world of cinema and music with our
                                        extensive library of articles, interviews, and reviews, designed to educate,
                                        inform, and inspire.
                                        </span>
                                    </p>

                                    <h2 class="display-3 text-center fw-bold mb-3 mb-xl-4">Our Vision</h2>
                                    <p class="lead">
                                        <span class="col-12 col-sm-11 col-lg-8 col-xl-7 col-xxl-6">
                                        We envision StoreLinks as more than just a website—it’s a community where
                                        culture and creativity meet. We believe in the transformative power of movies
                                        and music, and we’re dedicated to creating a space where these art forms can be
                                        appreciated, discussed, and enjoyed by everyone.
                                        </span>
                                    </p>

                                    <h2 class="display-3 text-center fw-bold mb-3 mb-xl-4">Join Us</h2>
                                    <p class="lead">
                                        <span class="col-12 col-sm-11 col-lg-8 col-xl-7 col-xxl-6">
                                        Whether you're here to discover something new, share your latest find, or simply
                                        organize your digital collection, StoreLinks is here to help you every step of
                                        the way. Join us on this exciting journey, and let’s celebrate the magic of
                                        movies and music together!
                                        </span>
                                    </p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

about/templates/about/contact.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


    <!-- Contact 6 - Bootstrap Brain Component -->
    <section class="py-3 py-md-5 py-xl-8 bg-white">
    <h2 class="visually-hidden">Contact form</h2>
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <div class="card border border-dark rounded shadow-sm overflow-hidden">
                        <div class="card-body p-0">
                            <div class="row gy-3 gy-md-4 gy-lg-0">
                                <div class="col-12 col-lg-6 bsb-overlay background-position-center background-size-cover">
                                    <div class="row align-items-lg-center justify-content-center h-100">
                                        <div class="col-11 col-xl-10">
                                            <div class="contact-info-wrapper py-4 py-xl-5">
                                                <h2 class="h1 mb-3 text-light">Get in touch</h2>
                                                <p class="lead fs-4 text-light opacity-75 mb-4 mb-xxl-5">We're
                                                    always on the lookout to work with new clients. If you're
                                                    interested in working with us, please get in touch in one of the
                                                    following ways.</p>
                                                <div class="row mb-4 mb-xxl-5">
                                                    <div class="col-12 col-xxl-6">
                                                        <div class="d-flex mb-4 mb-xxl-0">
                                                            <div class="me-4 text-primary">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="32"
                                                                     height="32" fill="currentColor"
                                                                     class="bi bi-telephone-outbound"
                                                                     viewBox="0 0 16 16">
                                                                    <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511zM11 .5a.5.5 0 0 1 .5-.5h4a.5.5 0 0 1 .5.5v4a.5.5 0 0 1-1 0V1.707l-4.146 4.147a.5.5 0 0 1-.708-.708L14.293 1H11.5a.5.5 0 0 1-.5-.5z"></path>
                                                                </svg>
                                                            </div>
                                                            <div>
                                                                <h4 class="mb-3 text-light">Phone</h4>
                                                                <p class="mb-0">
                                                                    <a class="link-light link-opacity-75 link-opacity-100-hover text-decoration-none"
                                                                       href="tel:+00000000000">(000) 000-0000</a>
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                    <div class="col-12 col-xxl-6">
                                                        <div class="d-flex mb-0">
                                                            <div class="me-4 text-primary">
                                                                <svg xmlns="http://www.w3.org/2000/svg" width="32"
                                                                     height="32" fill="currentColor"
                                                                     class="bi bi-envelope-at" viewBox="0 0 16 16">
                                                                    <path d="M2 2a2 2 0 0 0-2 2v8.01A2 2 0 0 0 2 14h5.5a.5.5 0 0 0 0-1H2a1 1 0 0 1-.966-.741l5.64-3.471L8 9.583l7-4.2V8.5a.5.5 0 0 0 1 0V4a2 2 0 0 0-2-2H2Zm3.708 6.208L1 11.105V5.383l4.708 2.825ZM1 4.217V4a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1v.217l-7 4.2-7-4.2Z"></path>
                                                                    <path d="M14.247 14.269c1.01 0 1.587-.857 1.587-2.025v-.21C15.834 10.43 14.64 9 12.52 9h-.035C10.42 9 9 10.36 9 12.432v.214C9 14.82 10.438 16 12.358 16h.044c.594 0 1.018-.074 1.237-.175v-.73c-.245.11-.673.18-1.18.18h-.044c-1.334 0-2.571-.788-2.571-2.655v-.157c0-1.657 1.058-2.724 2.64-2.724h.04c1.535 0 2.484 1.05 2.484 2.326v.118c0 .975-.324 1.39-.639 1.39-.232 0-.41-.148-.41-.42v-2.19h-.906v.569h-.03c-.084-.298-.368-.63-.954-.63-.778 0-1.259.555-1.259 1.4v.528c0 .892.49 1.434 1.26 1.434.471 0 .896-.227 1.014-.643h.043c.118.42.617.648 1.12.648Zm-2.453-1.588v-.227c0-.546.227-.791.573-.791.297 0 .572.192.572.708v.367c0 .573-.253.744-.564.744-.354 0-.581-.215-.581-.8Z"></path>
                                                                </svg>
                                                            </div>
                                                            <div>
                                                                <h4 class="mb-3 text-light">E-Mail</h4>
                                                                <p class="mb-0">
                                                                    <a class="link-light link-opacity-75 link-opacity-100-hover text-decoration-none"
                                                                       href="mailto:demo@yourdomain.com">demo@yourdomain.com</a>
                                                                </p>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>

                                            </div>
                                        </div>
                                    </div>
                                </div>

                                <div class="col-12 col-lg-6">
                                    <div class="row align-items-lg-center h-100">
                                        <div class="col-12">
                                            <form method="POST" action="{% url 'about:contact_us' %}">
                                                {% csrf_token %}
                                                <div class="row gy-4 gy-xl-5 p-4 p-xl-5">
                                                    <div class="col-12">
                                                        <label for="fullname" class="form-label">Full Name <span
                                                                class="text-danger">*</span></label>
                                                        <input type="text" class="form-control" id="fullname"
                                                               name="name" value="" required>
                                                    </div>
                                                    <div class="col-12 col-md-6">
                                                        <label for="email" class="form-label">Email <span
                                                                class="text-danger">*</span></label>
                                                        <div class="input-group">
                                <span class="input-group-text">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                       class="bi bi-envelope" viewBox="0 0 16 16">
                                    <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z"></path>
                                  </svg>
                                </span>
                                                            <input type="email" class="form-control" id="email"
                                                                   name="email" value="" required>
                                                        </div>
                                                    </div>
                                                    <div class="col-12 col-md-6">
                                                        <label for="phone" class="form-label">Phone Number</label>
                                                        <div class="input-group">
                                <span class="input-group-text">
                                  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
                                       class="bi bi-telephone" viewBox="0 0 16 16">
                                    <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z"></path>
                                  </svg>
                                </span>
                                                            <input type="tel" class="form-control" id="phone"
                                                                   name="phone" value="">
                                                        </div>
                                                    </div>
                                                    <div class="col-12">
                                                        <label for="subject" class="form-label">Subject <span
                                                                class="text-danger">*</span></label>
                                                        <input type="text" class="form-control" id="subject"
                                                               name="subject" value="" required>
                                                    </div>
                                                    <div class="col-12">
                                                        <label for="message" class="form-label">Message <span
                                                                class="text-danger">*</span></label>
                                                        <textarea class="form-control" id="message" name="message"
                                                                  rows="3" required></textarea>
                                                    </div>
                                                    <div class="col-12">
                                                        <div class="d-grid">
                                                            <button class="btn btn-dark btn-lg" type="submit">Send
                                                                Message
                                                            </button>
                                                        </div>
                                                    </div>
                                                </div>
                                            </form>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}