app/urls.py
from django.contrib import admin
from django.urls import path, include

from app.settings import DEBUG

urlpatterns = [
    path("about/", include("about.urls", namespace="about")),
    path("admin/", admin.site.urls),
    path("movies/", include("movie.urls", namespace="movies")),
    path("user/", include("users.urls", namespace="user")),
    path("", include("main.urls", namespace="main")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

main/urls.py
from django.urls import path

from . import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
]

movie/urls.py
from django.urls import path

from . import views

app_name = "movies"

urlpatterns = [
    path("", views.movie_catalog, name="movie_catalog"),
    path("search/", views.movie_catalog, name="movie_search"),
    path("<slug:genre_slug>/", views.movie_catalog, name="movie_genre"),
    path("movie/<slug:movie_slug>/", views.movie_detail, name="movie_detail"),
    path(
        "movie/<slug:slug>/edit_comment/<int:comment_id>/",
        views.comment_edit,
        name="comment_edit",
    ),
    path(
        "movie/<slug:slug>/delete_comment/<int:comment_id>/",
        views.comment_delete,
        name="comment_delete",
    ),
]

storelink/urls.py
from django.contrib import admin
from django.urls import path, include
from main.views import main

urlpatterns = [
    path("admin/", admin.site.urls),
    # path("", include("main.urls"), name="home"),
    path("", main, name="home"),
]

storelinks/urls.py
from django.contrib import admin
from django.urls import path, include

from storelinks.settings import DEBUG

urlpatterns = [
    path("", include("movie.urls", namespace="movie")),
    path("about/", include("about.urls", namespace="about")),
    path("accounts/", include("allauth.urls")),
    path("admin/", admin.site.urls),
    # path("movies/", include("movie.urls", namespace="movie")),
    path("summernote/", include("django_summernote.urls")),
]

if DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path("login/", views.login, name="login"),
    path("registration/", views.registration, name="registration"),
    path("profile/", views.profile, name="profile"),
    path("logout/", views.logout, name="logout"),
]

movie/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify

from app import settings

# Create your models here.

STATUS = ((0, "Draft"), (1, "Published"))


class Movie(models.Model):
	"""
	The Movie class represents a film with various descriptive attributes.
	"""

	title = models.CharField(max_length=255)
	year = models.CharField(max_length=10, blank=True, null=True)
	rated = models.CharField(max_length=10, blank=True, null=True)
	released = models.CharField(max_length=50, blank=True, null=True)
	runtime = models.CharField(max_length=20, blank=True, null=True)
	genres = models.ManyToManyField(
		"Genre", related_name="movies", blank=True
		)  # ManyToMany for Genres
	director = models.CharField(max_length=255, blank=True, null=True)
	writer = models.CharField(max_length=255, blank=True, null=True)
	actors = models.ManyToManyField(
		"Actor", related_name="movies", blank=True
		)  # ManyToMany for actors
	plot = models.TextField(blank=True, null=True)
	language = models.CharField(max_length=100, blank=True, null=True)
	country = models.CharField(max_length=100, blank=True, null=True)
	awards = models.TextField(blank=True, null=True)
	poster = models.URLField(blank=True, null=True)
	metascore = models.CharField(max_length=10, blank=True, null=True)
	imdb_rating = models.CharField(max_length=10, blank=True, null=True)
	imdb_votes = models.CharField(max_length=20, blank=True, null=True)
	imdb_id = models.CharField(
		max_length=20, unique=True, blank=True, null=True)
	type = models.CharField(max_length=50, blank=True, null=True)
	dvd = models.CharField(max_length=50, blank=True, null=True)
	box_office = models.CharField(max_length=50, blank=True, null=True)
	production = models.ForeignKey(
		"Production",
		related_name="movies",
		on_delete=models.SET_NULL,
		null=True,
		blank=True,
		)  # ForeignKey для студии
	website = models.URLField(blank=True, null=True)
	slug = models.SlugField(
		max_length=250, unique=True, blank=True, null=True, verbose_name="URL"
		)
	status = models.IntegerField(choices=STATUS, default=0)
	created_on = models.DateTimeField(auto_now_add=True)
	updated_on = models.DateTimeField(auto_now=True)

	class Meta:
		db_table = "movie"
		verbose_name = "Movie"
		verbose_name_plural = "Movies"
		ordering = ("id",)

	def __str__(self):
		return self.title

	def save(self, *args, **kwargs):
		if not self.slug or self.title != self.slug_to_title(self.slug):
			self.slug = self.generate_unique_slug()
		super().save(*args, **kwargs)

	def slug_to_title(self, slug):
		# Returns the original title из slug
		return slug.replace("-", " ").title()

	def generate_unique_slug(self):
		original_slug = slugify(self.title)
		unique_slug = original_slug
		counter = 1

		# Check whether such a slug already exists in the database
		while Movie.objects.filter(slug=unique_slug).exists():
			unique_slug = f"{original_slug}-{counter}"
			counter += 1

		return unique_slug


class Rating(models.Model):
	"""
	Represents a movie rating sourced from an external provider.
	"""

	movie = models.ForeignKey(
		"Movie", related_name="ratings", on_delete=models.CASCADE)
	source = models.CharField(max_length=100)
	value = models.CharField(max_length=20)

	class Meta:
		db_table = "rating"

	def __str__(self):
		return f"{self.source}: {self.value}"


class Actor(models.Model):
	"""
	Model representing an actor with capabilities to auto-generate a slug.
	"""

	name = models.CharField(max_length=255)
	slug = models.SlugField(max_length=270, unique=True, blank=True, null=True)

	class Meta:
		db_table = "actor"

	def save(self, *args, **kwargs):
		if not self.slug:
			# Generate a slug from the name
			self.slug = slugify(self.name)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.name


class Genre(models.Model):
	"""
	Represents a music genre with a name and a slug for URL usage.
	"""

	name = models.CharField(max_length=100, default="without_genre")
	slug = models.SlugField(max_length=250, unique=True, blank=True, null=True)

	class Meta:
		db_table = "genre"

	def save(self, *args, **kwargs):
		if not self.slug:
			# Generate a slug from the name
			self.slug = slugify(self.name)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.name


class Production(models.Model):
	"""
	Represents a production entity for storing production-related data.
	"""

	name = models.CharField(max_length=255)
	slug = models.SlugField(max_length=270, unique=True, blank=True, null=True)

	class Meta:
		db_table = "production"

	def save(self, *args, **kwargs):
		if not self.slug:
			# Generate a slug from the name
			self.slug = slugify(self.name)
		super().save(*args, **kwargs)

	def __str__(self):
		return self.name


class MovieComment(models.Model):
	"""
	Represents a comment related to a specific movie within a film database.
	"""

	movie = models.ForeignKey(
		Movie, on_delete=models.CASCADE, related_name="movie_comments"
		)
	author = models.ForeignKey(
		settings.AUTH_USER_MODEL,
		on_delete=models.CASCADE,
		related_name="comment_author",
		)
	body = models.TextField()
	approved = models.BooleanField(default=False)
	created_on = models.DateTimeField(auto_now_add=True)

	class Meta:
		db_table = "movie_comment"
		verbose_name = "Movie comment"
		verbose_name_plural = "Movie comments"
		ordering = [
			"-created_on",
			"author",
			"approved",
			]

	def __str__(self):
		return f"Comment {self.body} | written by {self.author}"

movie/forms.py
from django import forms

from movie.models import MovieComment


class MovieCommentForm(forms.ModelForm):
    class Meta:
        model = MovieComment
        fields = ('body',)

movie/views.py
from django.core.paginator import Paginator
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.contrib import messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .forms import MovieCommentForm

from .models import Genre, Movie, MovieComment
from .utils import q_search


def movie_catalog(request, genre_slug=None):
    """
   Handles the movie catalog view, filtering movies by genre, search query, and
pagination.
    """

    # Get the current page number from the request
    page_number = int(request.GET.get("page", 1))

    # Get the search parameter from query
    query = request.GET.get("q", None)

    # Use get_list_or_404 to get the list of movies with status=1
    if genre_slug == "all":
        movies_list = get_list_or_404(Movie.objects.filter(status=1))
    elif query:
        movies_list = get_list_or_404(q_search(query))
    else:
        movies_list = get_list_or_404(
            Movie.objects.filter(genres__slug=genre_slug))

    # Set up pagination, with 24 items per page and 3 orphans
    paginator = Paginator(movies_list, 24, orphans=3)

    # Get the movies for the current page
    page_obj = paginator.get_page(page_number)
    genre_name = get_object_or_404(Genre.objects.filter(slug=genre_slug))
    genre_title = genre_name.name if genre_name else "Movie Catalog"

    context = {
        "page_obj": page_obj,
        "slug_url": genre_slug,
        "title": genre_title.capitalize(),
        }

    # Pass the movies and page object to the template
    return render(request, "movie/index.html", context)


def movie_detail(request, movie_slug):
    """
    Handles the display of movie details including comments.
    """

    queryset = Movie.objects.filter(status=1)
    movie = get_object_or_404(queryset, slug=movie_slug)
    comments = movie.movie_comments.all().order_by("-created_on")
    comment_count = movie.movie_comments.filter(approved=True).count()

    if request.method == "POST":
        comment_form = MovieCommentForm(data=request.POST)
        if comment_form.is_valid():
            comment = comment_form.save(commit=False)
            comment.author = request.user
            comment.movie = movie
            comment.save()
            messages.add_message(
                request,
                messages.SUCCESS,
                "Comment submitted and need approval"
                )

    comment_form = MovieCommentForm()

    context = {
        "movie": movie,
        "comments": comments,
        "comment_count": comment_count,
        "comment_form": comment_form,
        "title": movie.title,
        }

    return render(
        request,
        "movie/movie_detail.html",
        context=context,
        )


def comment_edit(request, slug, comment_id):
    """
    Handles the editing of an existing comment on a movie post.
    """
    if request.method == "POST":

        queryset = Movie.objects.filter(status=1)
        movie = get_object_or_404(queryset, slug=slug)
        comment = get_object_or_404(MovieComment, pk=comment_id)
        comment_form = MovieCommentForm(data=request.POST, instance=comment)
        if comment_form.is_valid() and comment.author == request.user:
            comment = comment_form.save(commit=False)
            comment.movie = movie
            comment.approved = False
            comment.save()
            messages.add_message(request, messages.SUCCESS, "Comment Updated!")
        else:
            messages.add_message(
                request, messages.ERROR, "Error updating comment!")

    return HttpResponseRedirect(reverse("movies:movie_detail", args=[slug]))


def comment_delete(request, slug, comment_id):
    """
    Deletes a comment from a movie post if the request user is the author
    """
    queryset = Movie.objects.filter(status=1)
    movie = get_object_or_404(queryset, slug=slug)
    comment = get_object_or_404(MovieComment, pk=comment_id)

    if comment.author == request.user:
        comment.delete()
        messages.add_message(request, messages.SUCCESS, "Comment deleted!")
    else:
        messages.add_message(
            request, messages.ERROR, "You can only delete your own comments!"
            )

    return HttpResponseRedirect(reverse("movies:movie_detail", args=[slug]))


@login_required
def user_comments(request, slug, comment_id, action=None):
    comments = MovieComment.objects.filter(user=request.user)
    context = {
        "comments": comments,
        }
    return render(request, "movie/user_comments.html", context)

movie/templates/movie/comment.html
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block comments %}

    <!-- Displaying count of comments -->
    <div class="container">
        <div class="row">
            <div class="col-12">
                <strong class="text-secondary">
                    <i class="far fa-comments"></i> {{ comment_count }}
                </strong>
            </div>
            <div class="col-12">
                <hr/>
            </div>
        </div>

        <!-- Displaying Comments -->
        <div class="row">
            <div class="col-md-8 card mb-4 mt-3">
                <h3>Comments:</h3>
                <div class="card-body">
                    <!-- We want a for loop inside the empty control tags
                    to iterate through each comment in comments -->
                    {% for comment in comments %}
                        <div
                                class="p-2 comments {% if not comment.approved and comment.author == user %} faded{% elif not comment.approved %} d-none{% endif %}">
                            <p class="font-weight-bold">
                                {{ comment.author }}
                                <span class="font-weight-normal"> {{ comment.created_on }} </span>
                                wrote:
                            </p>
                            <div id="comment{{ comment.id }}">
                                {{ comment.body | linebreaks }}
                            </div>
                            {% if not comment.approved and comment.author == user %}
                                <p class="approval">This comment is awaiting approval</p>
                            {% endif %}
                            {% if user.is_authenticated and comment.author == user %}
                                <button class="btn btn-delete" data-comment_id="{{ comment.id }}">Delete</button>
                                <button class="btn btn-edit" data-comment_id="{{ comment.id }}">Edit</button>
                            {% endif %}
                        </div>
                        <!-- Our for loop ends here -->
                    {% endfor %}
                </div>
            </div>
            <!-- Creating New Comments -->
            <div class="col-md-4 card mb-4 mt-3">
                <div class="card-body">
                    {% if user.is_authenticated %}
                        <h3>Leave a comment:</h3>
                        <p>Posting as: {{ user.username }}</p>
                        <form id="commentForm" method="post" style="margin-top: 1.3em">
                            {{ comment_form | crispy }}
                            {% csrf_token %}
                            <button id="submitButton" type="submit" class="btn btn-signup btn-lg">
                                Submit
                            </button>
                        </form>
                    {% else %}
                        <p><a href="{% url 'user:login' %}">Log in</a> to leave a comment</p>
                    {% endif %}
                </div>
            </div>
        </div>

    </div>
{% endblock %}

movie/templates/movie/index.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
        <!-- Card 5 - Bootstrap Brain Component -->
        <section class="py-3 py-md-5 py-xl-8 bg-white">
            <h2 class="visually-hidden">Movie List</h2>
            <div class="container overflow-hidden">
                <div class="row gy-4 gy-xxl-5">
                    {% for movie in page_obj %}
                        <div class="col-12 col-sm-6 col-lg-4 col-xl-3">
                            <div class="card border border-dark"
                                 style="--bs-card-border-radius: 0; --bs-card-inner-border-radius: 0;">
                                <figure class="card-img-top m-0 overflow-hidden bsb-overlay-hover"
                                        style="height: 380px;">
                                    <a href="{% url 'movies:movie_detail' movie.slug %}">
                                        <img class="img-fluid w-100 h-100 bsb-scale bsb-hover-scale-up" loading="lazy"
                                             src="{{ movie.poster }}" alt="{{ movie.title }}"
                                             onerror="this.onerror=null; this.src='{% static 'images/no_image_poster.png' %}';"
                                             style="object-fit: cover;">
                                    </a>
                                    <figcaption class="p-3">
                                        <h2 class="h3 text-white text-center fw-bold mb-1 bsb-hover-fadeInRight">
                                            {{ movie.title }}
                                        </h2>
                                        <p class="fs-9 m-0 px-4 text-white text-center bsb-hover-fadeInUp">
                                            {{ movie.plot }}
                                        </p>
                                    </figcaption>
                                </figure>
                            </div>
                        </div>

                    {% endfor %}
                </div>
            </div>
            <!-- Pagination -->
            {% with movie_list as list_obj %}
                {% include 'pagination.html' %}
            {% endwith %}

        </section>




{% endblock %}

movie/templates/movie/movie_detail.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}

    <section class="py-3 py-md-5 py-xl-8">
        <div class="container overflow-hidden">
            <div class="row gy-4 gy-xxl-5">
                <div class="col-md-4">
                    <img src="{{ movie.poster }}" alt="{{ movie.title }} Poster" class="img-fluid"
                         onerror="this.onerror=null; this.src='{% static 'images/no_image_poster.png' %}';"
                         style="object-fit: cover;">
                </div>
                <div class="col-md-8">
                    <h1>{{ movie.title }}</h1>
                    <p><strong>Year:</strong> {{ movie.year }}</p>
                    <p><strong>Rated:</strong> {{ movie.rated }}</p>
                    <p><strong>Released:</strong> {{ movie.released }}</p>
                    <p><strong>Runtime:</strong> {{ movie.runtime }}</p>
                    <p><strong>Genres:</strong>
                        {% for genre in movie.genres.all %}
                            {{ genre.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <p><strong>Director:</strong> {{ movie.director }}</p>
                    <p><strong>Writer:</strong> {{ movie.writer }}</p>
                    <p><strong>Actors:</strong>
                        {% for actor in movie.actors.all %}
                            {{ actor.name }}{% if not forloop.last %}, {% endif %}
                        {% endfor %}
                    </p>
                    <p><strong>Plot:</strong> {{ movie.plot }}</p>
                    <p><strong>Language:</strong> {{ movie.language }}</p>
                    <p><strong>Country:</strong> {{ movie.country }}</p>
                    <p><strong>Awards:</strong> {{ movie.awards }}</p>
                    <p><strong>Metascore:</strong> {{ movie.metascore }}</p>
                    <p><strong>IMDb Rating:</strong> {{ movie.imdb_rating }}</p>
                    <p><strong>IMDb Votes:</strong> {{ movie.imdb_votes }}</p>
                    <p><strong>Box Office:</strong> {{ movie.box_office }}</p>
                    <p><strong>Production:</strong> {{ movie.production.name }}</p>
                    <p><strong>Website:</strong> <a href="{{ movie.website }}" target="_blank">{{ movie.website }}</a>
                    </p>
                </div>
            </div>
            <div class="mt-4">
                <a href="{% url 'main:index' %}" class="btn btn-dark btn-block">Back to Home</a>
            </div>
        </div>
    </section>
    <section>
        {% block comments %}
            {% include 'movie/comment.html' %}
        {% endblock %}
    </section>




{% endblock %}

movie/templates/movie/user_comments.html
{% for comment in comments %}
    <div class="accordion-item mb-4 border border-dark">
        <h2 class="accordion-header" id="headingThree">
            {{ comment.body }} - {{ comment.approved }}
        </h2>

    </div>

{% endfor %}